const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),pasteCatcher=$('pasteCatcher');
let img=null,imgW=0,imgH=0,view={scale:1,offsetX:0,offsetY:0},dpr=devicePixelRatio||1,pointers=new Map(),lastPinchDist=null,pointerDownInfo=null,suppressNextTap=false;
let tiles=[],nextId=1,traySlots=[],trayCounts=new Map(),suggestionId=null,history=[],editMode=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const colors=['#00C853','#2962FF','#AA00FF','#FF6D00','#00B8D4','#D50000','#C51162','#64DD17','#6200EA','#0091EA','#795548','#607D8B','#F50057','#C0CA33'];
function colorForType(i){return colors[((i||1)-1)%colors.length]}
function rect(){return canvas.getBoundingClientRect()}function disp(){let r=rect(),w=Math.max(320,r.width||canvas.parentElement.clientWidth||360);return{width:w,height:img?w*imgH/imgW:w*1.6}}function baseScale(){return img?disp().width/imgW:1}
function cssToImage(x,y){let s=baseScale()*view.scale;return{ix:(x-view.offsetX)/s,iy:(y-view.offsetY)/s}}function clientToImage(x,y){let r=rect();return cssToImage(x-r.left,y-r.top)}
function resizeCanvas(){dpr=devicePixelRatio||1;let d=disp();canvas.style.height=d.height+'px';canvas.width=Math.round(d.width*dpr);canvas.height=Math.round(d.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function draw(){let d=disp();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,d.width,d.height);if(!img){ctx.fillStyle='#f2f2f2';ctx.fillRect(0,0,d.width,d.height);ctx.fillStyle='#777';ctx.font='14px system-ui';ctx.fillText('Paste หรือ Upload รูปก่อน',16,28);return}ctx.save();let s=baseScale()*view.scale;ctx.translate(view.offsetX,view.offsetY);ctx.scale(s,s);ctx.drawImage(img,0,0,imgW,imgH);for(let t of tiles){let x=t.cx-t.w/2,y=t.cy-t.h/2;ctx.globalAlpha=t.active?1:.33;ctx.setLineDash(t.active?[]:[8/s,5/s]);ctx.lineWidth=(t.selected?5:3)/s;ctx.strokeStyle=t.selected?'#FFD600':t.color;ctx.strokeRect(x,y,t.w,t.h);ctx.fillStyle='rgba(0,0,0,.72)';ctx.font=`${14/s}px system-ui`;ctx.fillText(`${t.active?'':'D-'}T${t.typeId}`,x+4/s,y+16/s);ctx.globalAlpha=1;ctx.setLineDash([]);if(t.id===suggestionId){ctx.lineWidth=7/s;ctx.strokeStyle='#ff1744';ctx.strokeRect(x-4/s,y-4/s,t.w+8/s,t.h+8/s)}}ctx.restore()}
function renderTray(){let v=$('trayView');v.innerHTML='';for(let i=0;i<7;i++){let s=document.createElement('div');s.className='slot';if(i<traySlots.length){let t=traySlots[i];s.textContent='T'+t;s.style.color=colorForType(t);s.style.borderColor=colorForType(t)}v.appendChild(s)}$('trayMeta').textContent=`ขนาดถาด: ${traySlots.length}/7 • นับ: ${[...trayCounts.entries()].map(([k,v])=>`T${k}:${v}`).join(' ')||'-'}`}
function syncTray(){trayCounts=new Map();for(let t of traySlots)trayCounts.set(t,(trayCounts.get(t)||0)+1)}
function reset(){tiles=[];nextId=1;traySlots=[];trayCounts=new Map();suggestionId=null;history=[];renderTray();draw()}
async function setImageBlob(blob){let url=URL.createObjectURL(blob),im=new Image();im.onload=()=>{img=im;imgW=im.naturalWidth;imgH=im.naturalHeight;view={scale:1,offsetX:0,offsetY:0};reset();let sz=Math.round(clamp(imgW/9,60,115));$('tileSize').value=sz;$('tileSizeLabel').textContent=sz;resizeCanvas();$('result').textContent='โหลดรูปแล้ว กด “วิเคราะห์รูป”'};im.onerror=()=>$('result').textContent='อ่านรูปไม่สำเร็จ';im.src=url}
async function paste(){try{if(navigator.clipboard&&navigator.clipboard.read){let items=await navigator.clipboard.read();for(let it of items){let type=it.types.find(t=>t.startsWith('image/'));if(type){await setImageBlob(await it.getType(type));return}}}}catch(e){}$('result').textContent='ถ้า iOS ไม่อนุญาตอ่าน clipboard ให้แตะค้างแล้วเลือก Paste';pasteCatcher.focus()}
function centerCrop(ix,iy,size){let c=document.createElement('canvas');c.width=64;c.height=64;let g=c.getContext('2d');let sx=ix-size*.25,sy=iy-size*.28,sw=size*.50,sh=size*.56;sx=clamp(sx,0,imgW-sw);sy=clamp(sy,0,imgH-sh);g.drawImage(img,sx,sy,sw,sh,0,0,64,64);return c}
function feature(ix,iy,size){let c=centerCrop(ix,iy,size),g=c.getContext('2d'),data=g.getImageData(0,0,64,64).data;let gray=[],hist=new Array(24).fill(0);for(let i=0;i<data.length;i+=4){let r=data[i],gg=data[i+1],b=data[i+2];gray.push(r*.299+gg*.587+b*.114);hist[Math.min(7,Math.floor(r/32))]++;hist[8+Math.min(7,Math.floor(gg/32))]++;hist[16+Math.min(7,Math.floor(b/32))]++}let bits=new Uint8Array(64),k=0;for(let y=0;y<8;y++)for(let x=0;x<8;x++){let sum=0;for(let yy=0;yy<8;yy++)for(let xx=0;xx<8;xx++)sum+=gray[(y*8+yy)*64+(x*8+xx)];bits[k++]=sum/64>128?1:0}let norm=Math.sqrt(hist.reduce((a,b)=>a+b*b,0))||1;hist=hist.map(v=>v/norm);return{bits,hist}}
function dist(a,b){let h=0;for(let i=0;i<a.bits.length;i++)if(a.bits[i]!==b.bits[i])h++;let dot=0;for(let i=0;i<a.hist.length;i++)dot+=a.hist[i]*b.hist[i];return h/64*.62+(1-dot)*.38}
function learnTypes(){let reps=[];for(let t of tiles){let best=null;for(let r of reps){let d=dist(t.feat,r.feat);if(!best||d<best.d)best={r,d}}if(best&&best.d<.27){t.typeId=best.r.typeId;best.r.count++}else{t.typeId=reps.length+1;reps.push({typeId:t.typeId,feat:t.feat,count:1})}t.color=colorForType(t.typeId)}draw();return reps.length}
function addTile(ix,iy,active=true){let size=parseInt($('tileSize').value,10);if(ix<0||iy<0||ix>imgW||iy>imgH)return null;let t={id:nextId++,cx:ix,cy:iy,w:size,h:size,feat:feature(ix,iy,size),typeId:1,color:'#999',active,selected:false};tiles.push(t);learnTypes();return t}
function hit(ix,iy){for(let i=tiles.length-1;i>=0;i--){let t=tiles[i];if(ix>=t.cx-t.w/2&&ix<=t.cx+t.w/2&&iy>=t.cy-t.h/2&&iy<=t.cy+t.h/2)return t}return null}
function iou(a,b){let ax0=a.cx-a.w/2,ay0=a.cy-a.h/2,ax1=a.cx+a.w/2,ay1=a.cy+a.h/2,bx0=b.cx-b.w/2,by0=b.cy-b.h/2,bx1=b.cx+b.w/2,by1=b.cy+b.h/2,ix=Math.max(0,Math.min(ax1,bx1)-Math.max(ax0,bx0)),iy=Math.max(0,Math.min(ay1,by1)-Math.max(ay0,by0)),inter=ix*iy,u=a.w*a.h+b.w*b.h-inter;return u?inter/u:0}
function stats(data,x0,y0,w,h,stride){let W=data.width,A=data.data,n=0,sum=0,sum2=0,edge=0;x0=clamp(Math.floor(x0),0,W-1);y0=clamp(Math.floor(y0),0,data.height-1);let x1=clamp(Math.floor(x0+w),0,W-1),y1=clamp(Math.floor(y0+h),0,data.height-1);for(let y=y0;y<y1;y+=stride)for(let x=x0;x<x1;x+=stride){let p=(y*W+x)*4,br=(A[p]+A[p+1]+A[p+2])/3;sum+=br;sum2+=br*br;n++;if(x+stride<x1&&y+stride<y1){let p2=(y*W+x+stride)*4,p3=((y+stride)*W+x)*4,br2=(A[p2]+A[p2+1]+A[p2+2])/3,br3=(A[p3]+A[p3+1]+A[p3+2])/3;edge+=Math.abs(br-br2)+Math.abs(br-br3)}}let mean=sum/Math.max(1,n),variance=sum2/Math.max(1,n)-mean*mean;return{mean,variance,edge:edge/Math.max(1,n)}}
function detectTiles(autoActive=true){if(!img){$('result').textContent='โหลดรูปก่อน';return 0}tiles=[];nextId=1;suggestionId=null;let size=parseInt($('tileSize').value,10),sens=parseInt($('sens').value,10),scale=Math.min(1,900/imgW),pc=document.createElement('canvas');pc.width=Math.round(imgW*scale);pc.height=Math.round(imgH*scale);let p=pc.getContext('2d');p.drawImage(img,0,0,pc.width,pc.height);let data=p.getImageData(0,0,pc.width,pc.height),ss=size*scale,step=Math.max(10,Math.round(ss/3.3)),cand=[];for(let y=ss/2;y<pc.height-ss/2;y+=step)for(let x=ss/2;x<pc.width-ss/2;x+=step){let st=stats(data,x-ss/2,y-ss/2,ss,ss,Math.max(2,Math.round(ss/18))),inner=stats(data,x-ss*.25,y-ss*.28,ss*.5,ss*.56,Math.max(2,Math.round(ss/20)));let score=(st.mean-95)*1.05+Math.sqrt(Math.max(0,inner.variance))*2.15+st.edge*.5;if(st.mean>92&&inner.variance>145&&score>128-sens)cand.push({cx:x/scale,cy:y/scale,w:size,h:size,score})}cand.sort((a,b)=>b.score-a.score);let sel=[];for(let c of cand){if(sel.length>=70)break;if(sel.every(o=>iou(c,o)<.25))sel.push(c)}for(let c of sel)addTile(c.cx,c.cy,autoActive);learnTypes();draw();return tiles.length}
function analyze(){let n=detectTiles(true);let types=learnTypes();if(!n){$('result').textContent='ตรวจไม่พบไพ่ ลองเพิ่มความไวหรือแตะเพิ่มเองในโหมดแก้ไข';return}suggest();$('result').innerHTML+=`<br><span class="small">ตรวจพบ ${n} กรอบ / ประมาณ ${types} type — หากกรอบแดงผิด กด ✏️ แก้ไข</span>`}
function suggest(){learnTypes();let pool=tiles.filter(t=>t.active);if(!pool.length){suggestionId=null;draw();$('result').textContent='ยังไม่มีไพ่ที่ Active';return false}let cnt=new Map();for(let t of pool)cnt.set(t.typeId,(cnt.get(t.typeId)||0)+1);let trayTypes=new Set(traySlots),best=null;for(let t of pool){let inTray=trayCounts.get(t.typeId)||0,score=0,reason=[];if(inTray===2){score+=1000;reason.push('ปิดครบ 3')}else if(inTray===1){score+=220;reason.push('ทำเป็นคู่')}if((cnt.get(t.typeId)||0)>=2){score+=75;reason.push('มีชนิดเดียวกันหลายใบ')}if(traySlots.length>=5&&!trayTypes.has(t.typeId)){score-=180;reason.push('ถาดใกล้เต็ม')}if(trayTypes.has(t.typeId))score+=45;score+=(1000-t.id)*1e-6;if(!best||score>best.score)best={tile:t,reason}}suggestionId=best.tile.id;draw();$('result').innerHTML=`แนะนำให้กด <b>T${best.tile.typeId}</b> (กรอบแดง) • ${best.reason.join(' • ')||'คะแนนดีที่สุด'}`;return true}
function addTray(type){if(traySlots.length>=7)return{ok:false};traySlots.push(type);syncTray();let cleared=false;if(trayCounts.get(type)===3){let r=0;traySlots=traySlots.filter(t=>(t===type&&r++<3)?false:true);syncTray();cleared=true}renderTray();return{ok:true,cleared}}
function apply(){if(!suggestionId&&!suggest())return;let idx=tiles.findIndex(t=>t.id===suggestionId);if(idx<0)return;history.push({tiles:tiles.map(t=>({...t,feat:{bits:new Uint8Array(t.feat.bits),hist:[...t.feat.hist]}})),tray:[...traySlots],nextId,suggestionId});let t=tiles[idx],r=addTray(t.typeId);tiles.splice(idx,1);suggestionId=null;learnTypes();draw();$('result').textContent=`บันทึกว่าได้กด T${t.typeId} แล้ว${r.cleared?' • ครบ 3 ลบแล้ว':''}`;setTimeout(suggest,50)}
function undo(){let h=history.pop();if(!h){$('result').textContent='ไม่มีประวัติ Undo';return}tiles=h.tiles.map(t=>({...t,feat:{bits:new Uint8Array(t.feat.bits),hist:[...t.feat.hist]}}));traySlots=[...h.tray];syncTray();nextId=h.nextId;suggestionId=h.suggestionId;renderTray();draw();$('result').textContent='Undo แล้ว'}
function selected(){return tiles.filter(t=>t.selected)}function merge(){let s=selected();if(s.length<2){$('result').textContent='เลือกอย่างน้อย 2 ใบก่อนรวม Type';return}let type=s[0].typeId;for(let t of s){t.typeId=type;t.color=colorForType(type);t.selected=false}draw();$('result').textContent='รวม Type แล้ว'}function split(){let s=selected();if(!s.length){$('result').textContent='เลือกใบก่อนแยก Type';return}let mx=Math.max(0,...tiles.map(t=>t.typeId))+1;for(let t of s){t.typeId=mx++;t.color=colorForType(t.typeId);t.selected=false}draw();$('result').textContent='แยก Type ใหม่แล้ว'}
function delSel(){let before=tiles.length;tiles=tiles.filter(t=>!t.selected);suggestionId=null;learnTypes();draw();$('result').textContent=`ลบ ${before-tiles.length} ใบแล้ว`}
function tap(x,y){if(!img)return;let p=clientToImage(x,y),t=hit(p.ix,p.iy);if(t){if(editMode){t.selected=!t.selected}else{t.active=!t.active}suggestionId=null;draw();return}if(editMode){let nt=addTile(p.ix,p.iy,true);if(nt){nt.selected=true;draw();$('result').textContent='เพิ่มไพ่เองแล้ว'}}}
$('upload').onchange=e=>{let f=e.target.files[0];if(f)setImageBlob(f)};$('btnPaste').onclick=paste;$('btnAnalyze').onclick=analyze;$('btnApply').onclick=apply;$('btnUndo').onclick=undo;$('btnSuggest').onclick=suggest;$('btnReset').onclick=()=>{reset();$('result').textContent='ล้างข้อมูลแล้ว'};$('btnClearTray').onclick=()=>{traySlots=[];syncTray();renderTray();$('result').textContent='ล้างถาดแล้ว'};$('btnEdit').onclick=()=>{editMode=!editMode;$('editPanel').classList.toggle('hidden',!editMode);$('btnEdit').textContent=editMode?'✅ ปิดแก้ไข':'✏️ แก้ไข';for(let t of tiles)t.selected=false;draw()};$('btnRedetect').onclick=()=>{let n=detectTiles(false);$('result').textContent=`Detect ใหม่แบบ Draft ${n} กรอบ — แตะเปิด/เลือกในโหมดแก้ไข`};$('btnLearn').onclick=()=>{$('result').textContent=`Learn Type ใหม่แล้ว: ${learnTypes()} type`};$('btnMerge').onclick=merge;$('btnSplit').onclick=split;$('btnDelete').onclick=delSel;$('tileSize').oninput=e=>$('tileSizeLabel').textContent=e.target.value;$('sens').oninput=e=>$('sensLabel').textContent=e.target.value;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)pointerDownInfo={x:e.clientX,y:e.clientY,time:Date.now()};if(pointers.size===2){let a=[...pointers.values()];lastPinchDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);suppressNextTap=true}});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;let prev=pointers.get(e.pointerId),cur={x:e.clientX,y:e.clientY};pointers.set(e.pointerId,cur);if(pointers.size===1){let dx=cur.x-prev.x,dy=cur.y-prev.y;if(Math.abs(dx)+Math.abs(dy)>1){view.offsetX+=dx;view.offsetY+=dy;draw()}}else if(pointers.size===2){let a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(lastPinchDist){let factor=dist/lastPinchDist,newScale=clamp(view.scale*factor,.5,5),r=rect(),mx=(a[0].x+a[1].x)/2-r.left,my=(a[0].y+a[1].y)/2-r.top,before=cssToImage(mx,my);view.scale=newScale;let s=baseScale()*view.scale;view.offsetX=mx-before.ix*s;view.offsetY=my-before.iy*s;draw()}lastPinchDist=dist}});function end(e){let single=pointers.size===1&&pointers.has(e.pointerId);pointers.delete(e.pointerId);if(pointers.size<2)lastPinchDist=null;if(single&&pointerDownInfo&&!suppressNextTap){let moved=Math.hypot(e.clientX-pointerDownInfo.x,e.clientY-pointerDownInfo.y),elapsed=Date.now()-pointerDownInfo.time;if(moved<8&&elapsed<700)tap(e.clientX,e.clientY)}if(pointers.size===0){pointerDownInfo=null;setTimeout(()=>suppressNextTap=false,50)}}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);pointerDownInfo=null;suppressNextTap=false});pasteCatcher.addEventListener('paste',async e=>{let cd=e.clipboardData;if(!cd)return;if(cd.items){for(let it of cd.items){if(it.type&&it.type.startsWith('image/')){let b=it.getAsFile();if(b){e.preventDefault();await setImageBlob(b);return}}}}$('result').textContent='Paste ไม่พบรูป'});window.addEventListener('resize',()=>{if(img)resizeCanvas()});renderTray();resizeCanvas();