const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),pasteCatcher=$('pasteCatcher');
const META=[['T01','blue_microphones'],['T02','purple_guitar'],['T03','pink_drum'],['T04','blue_music_note'],['T05','green_music_notes'],['T06','blue_drum_set'],['T07','blue_turntable'],['T08','pink_record_disc'],['T09','pink_headphones'],['T10','black_piano'],['T11','red_keyboard'],['T12','yellow_tambourine'],['T13','orange_accordion']].map((x,i)=>({id:i+1,code:x[0],name:x[1],file:`templates/${x[0]}_${x[1]}.jpeg`}));
const colors=['#00C853','#2962FF','#AA00FF','#FF6D00','#00B8D4','#D50000','#C51162','#64DD17','#6200EA','#0091EA','#795548','#607D8B','#F50057'];
let templates=[],img=null,imgW=0,imgH=0,dpr=devicePixelRatio||1,tiles=[],nextId=1,traySlots=[],trayCounts=new Map(),suggestionId=null,history=[],editMode=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const colorForType=i=>colors[((i||1)-1)%colors.length];
function disp(){let w=Math.max(320,canvas.parentElement.clientWidth||360);return{width:w,height:img?w*imgH/imgW:w*1.6}}function scale(){return img?disp().width/imgW:1}function clientToImage(x,y){let r=canvas.getBoundingClientRect(),s=scale();return{ix:(x-r.left)/s,iy:(y-r.top)/s}}
function resize(){dpr=devicePixelRatio||1;let d=disp();canvas.style.height=d.height+'px';canvas.width=Math.round(d.width*dpr);canvas.height=Math.round(d.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function draw(){let d=disp(),s=scale();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,d.width,d.height);if(!img){ctx.fillStyle='#f2f2f2';ctx.fillRect(0,0,d.width,d.height);ctx.fillStyle='#777';ctx.font='14px system-ui';ctx.fillText('Paste หรือ Upload รูปก่อน',16,28);return}ctx.drawImage(img,0,0,d.width,d.height);ctx.save();ctx.scale(s,s);for(let t of tiles){let x=t.cx-t.w/2,y=t.cy-t.h/2;ctx.globalAlpha=t.active?1:.28;ctx.setLineDash(t.active?[]:[6/s,4/s]);ctx.lineWidth=(t.selected?5:3)/s;ctx.strokeStyle=t.selected?'#FFD600':t.color;ctx.strokeRect(x,y,t.w,t.h);ctx.fillStyle='rgba(0,0,0,.75)';ctx.font=`${13/s}px system-ui`;ctx.fillText(`T${String(t.typeId).padStart(2,'0')} ${Math.round(t.conf*100)}%`,x+2/s,y+13/s);ctx.globalAlpha=1;ctx.setLineDash([]);if(t.id===suggestionId){ctx.lineWidth=7/s;ctx.strokeStyle='#ff1744';ctx.strokeRect(x-3/s,y-3/s,t.w+6/s,t.h+6/s)}}ctx.restore()}
function syncTray(){trayCounts=new Map();for(let t of traySlots)trayCounts.set(t,(trayCounts.get(t)||0)+1)}function renderTray(){let v=$('trayView');v.innerHTML='';for(let i=0;i<7;i++){let el=document.createElement('div');el.className='slot';if(i<traySlots.length){let t=traySlots[i];el.textContent='T'+String(t).padStart(2,'0');el.style.color=colorForType(t);el.style.borderColor=colorForType(t)}v.appendChild(el)}$('trayMeta').textContent=`ขนาดถาด: ${traySlots.length}/7 • ${[...trayCounts.entries()].map(([k,v])=>`T${String(k).padStart(2,'0')}:${v}`).join(' ')||'-'}`}
function reset(){tiles=[];nextId=1;traySlots=[];trayCounts=new Map();suggestionId=null;history=[];renderTray();draw()}
async function setImageBlob(blob){let url=URL.createObjectURL(blob),im=new Image();im.onload=()=>{img=im;imgW=im.naturalWidth;imgH=im.naturalHeight;reset();resize();$('result').textContent='โหลดรูปแล้ว กด “วิเคราะห์ Icon”'};im.src=url}
async function paste(){try{let items=await navigator.clipboard.read();for(let it of items){let type=it.types.find(t=>t.startsWith('image/'));if(type){await setImageBlob(await it.getType(type));return}}}catch(e){}$('result').textContent='ถ้า iOS ไม่อนุญาต ให้แตะค้างแล้ว Paste';pasteCatcher.focus()}
function featureCanvas(c){let g=c.getContext('2d'),data=g.getImageData(0,0,48,48).data,hist=new Array(36).fill(0),gray=[];for(let i=0;i<data.length;i+=4){let r=data[i],gg=data[i+1],b=data[i+2];gray.push(r*.299+gg*.587+b*.114);hist[Math.min(11,Math.floor(r/22))]++;hist[12+Math.min(11,Math.floor(gg/22))]++;hist[24+Math.min(11,Math.floor(b/22))]++}let bits=new Uint8Array(36),k=0;for(let y=0;y<6;y++)for(let x=0;x<6;x++){let sum=0;for(let yy=0;yy<8;yy++)for(let xx=0;xx<8;xx++)sum+=gray[(y*8+yy)*48+(x*8+xx)];bits[k++]=sum/64>128?1:0}let n=Math.sqrt(hist.reduce((a,b)=>a+b*b,0))||1;return{bits,hist:hist.map(v=>v/n)}}
function iconCropFromTemplate(im){let c=document.createElement('canvas');c.width=48;c.height=48;let g=c.getContext('2d'),w=im.naturalWidth,h=im.naturalHeight;g.drawImage(im,w*.22,h*.18,w*.56,h*.62,0,0,48,48);return c}
function cropIcon(ix,iy,size){let c=document.createElement('canvas');c.width=48;c.height=48;let g=c.getContext('2d'),sx=clamp(ix-size/2,0,imgW-size),sy=clamp(iy-size/2,0,imgH-size);g.drawImage(img,sx,sy,size,size,0,0,48,48);return c}
function dist(a,b){let h=0;for(let i=0;i<a.bits.length;i++)if(a.bits[i]!=b.bits[i])h++;let dot=0;for(let i=0;i<a.hist.length;i++)dot+=a.hist[i]*b.hist[i];return h/36*.45+(1-dot)*.55}
function classify(feat){let best=null,second=null;for(let t of templates){let d=dist(feat,t.feat);if(!best||d<best.d){second=best;best={t,d}}else if(!second||d<second.d)second={t,d}}let margin=second?second.d-best.d:0,conf=clamp(1-best.d/.48+margin*.45,0,1);return{typeId:best.t.id,conf,name:best.t.name}}
function addIcon(ix,iy,active=true){let size=parseInt($('iconSize').value,10),feat=featureCanvas(cropIcon(ix,iy,size)),cls=classify(feat),thr=parseInt($('confThreshold').value,10)/100;let t={id:nextId++,cx:ix,cy:iy,w:size,h:size,typeId:cls.typeId,conf:cls.conf,color:colorForType(cls.typeId),active:active&&cls.conf>=thr,selected:false};tiles.push(t);draw();return t}
function iou(a,b){let ax0=a.cx-a.w/2,ay0=a.cy-a.h/2,ax1=a.cx+a.w/2,ay1=a.cy+a.h/2,bx0=b.cx-b.w/2,by0=b.cy-b.h/2,bx1=b.cx+b.w/2,by1=b.cy+b.h/2,ix=Math.max(0,Math.min(ax1,bx1)-Math.max(ax0,bx0)),iy=Math.max(0,Math.min(ay1,by1)-Math.max(ay0,by0)),inter=ix*iy,u=a.w*a.h+b.w*b.h-inter;return u?inter/u:0}
function detectIcons(){if(!img){$('result').textContent='โหลดรูปก่อน';return 0}tiles=[];nextId=1;suggestionId=null;let size=parseInt($('iconSize').value,10),thr=parseInt($('confThreshold').value,10)/100,step=Math.max(10,Math.round(size*.55)),cand=[];for(let y=size/2;y<imgH-size/2;y+=step){for(let x=size/2;x<imgW-size/2;x+=step){let feat=featureCanvas(cropIcon(x,y,size)),cls=classify(feat);if(cls.conf>=thr)cand.push({cx:x,cy:y,w:size,h:size,cls,score:cls.conf})}}cand.sort((a,b)=>b.score-a.score);let sel=[];for(let c of cand){if(sel.length>=80)break;if(sel.every(o=>iou(c,o)<.22))sel.push(c)}for(let c of sel){let t={id:nextId++,cx:c.cx,cy:c.cy,w:size,h:size,typeId:c.cls.typeId,conf:c.cls.conf,color:colorForType(c.cls.typeId),active:true,selected:false};tiles.push(t)}draw();return tiles.length}
function analyze(){let n=detectIcons();if(!n){$('result').textContent='ไม่พบ icon ที่ match template เกิน threshold ลองลด Confidence หรือปรับขนาด Icon';return}suggest();$('result').innerHTML+=`<br><span class="small">พบ icon ที่ match template ${n} จุด (ตัดสิ่งที่ไม่ match template ออกแล้ว)</span>`}
function suggest(){let pool=tiles.filter(t=>t.active);if(!pool.length){suggestionId=null;draw();$('result').textContent='ไม่มี icon ที่ Active';return false}let cnt=new Map();for(let t of pool)cnt.set(t.typeId,(cnt.get(t.typeId)||0)+1);let trayTypes=new Set(traySlots),best=null;for(let t of pool){let inTray=trayCounts.get(t.typeId)||0,score=t.conf*20,reason=[];if(inTray===2){score+=1000;reason.push('ปิดครบ 3')}else if(inTray===1){score+=220;reason.push('ทำเป็นคู่')}if((cnt.get(t.typeId)||0)>=2){score+=75;reason.push('มีชนิดเดียวกันหลายใบ')}if(traySlots.length>=5&&!trayTypes.has(t.typeId)){score-=180;reason.push('ถาดใกล้เต็ม')}if(trayTypes.has(t.typeId))score+=45;if(!best||score>best.score)best={tile:t,score,reason}}suggestionId=best.tile.id;draw();$('result').innerHTML=`แนะนำให้กด <b>T${String(best.tile.typeId).padStart(2,'0')}</b> (กรอบแดงรอบ icon) • ${best.reason.join(' • ')||'คะแนนดีที่สุด'} • confidence ${Math.round(best.tile.conf*100)}%`;return true}
function addTray(type){if(traySlots.length>=7)return{ok:false};traySlots.push(type);syncTray();let cleared=false;if(trayCounts.get(type)===3){let r=0;traySlots=traySlots.filter(t=>(t===type&&r++<3)?false:true);syncTray();cleared=true}renderTray();return{ok:true,cleared}}
function apply(){if(!suggestionId&&!suggest())return;let idx=tiles.findIndex(t=>t.id===suggestionId);if(idx<0)return;history.push({tiles:tiles.map(t=>({...t})),tray:[...traySlots],nextId,suggestionId});let t=tiles[idx],r=addTray(t.typeId);tiles.splice(idx,1);suggestionId=null;draw();$('result').textContent=`บันทึกว่าได้กด T${String(t.typeId).padStart(2,'0')} แล้ว${r.cleared?' • ครบ 3 ลบแล้ว':''}`;setTimeout(suggest,50)}
function undo(){let h=history.pop();if(!h){$('result').textContent='ไม่มีประวัติ Undo';return}tiles=h.tiles;traySlots=h.tray;syncTray();nextId=h.nextId;suggestionId=h.suggestionId;renderTray();draw();$('result').textContent='Undo แล้ว'}
function hit(ix,iy){for(let i=tiles.length-1;i>=0;i--){let t=tiles[i];if(ix>=t.cx-t.w/2&&ix<=t.cx+t.w/2&&iy>=t.cy-t.h/2&&iy<=t.cy+t.h/2)return t}return null}
function tap(x,y){if(!img)return;let p=clientToImage(x,y),t=hit(p.ix,p.iy);if(t){if(editMode)t.selected=!t.selected;else t.active=!t.active;suggestionId=null;draw();return}if(editMode){let nt=addIcon(p.ix,p.iy,true);nt.selected=true;draw();$('result').textContent='เพิ่ม icon เองแล้ว'}}
function selected(){return tiles.filter(t=>t.selected)}function delSel(){let b=tiles.length;tiles=tiles.filter(t=>!t.selected);draw();$('result').textContent=`ลบ ${b-tiles.length} จุด`}function toggleSel(){let s=selected();for(let t of s){t.active=!t.active;t.selected=false}draw()}function setType(){let s=selected(),type=parseInt($('typeSelect').value,10);for(let t of s){t.typeId=type;t.color=colorForType(type);t.conf=1;t.active=true;t.selected=false}draw()}
async function loadTemplates(){let tv=$('templateView'),sel=$('typeSelect');for(let m of META){let im=new Image();im.src=m.file;await new Promise((res,rej)=>{im.onload=res;im.onerror=rej});let feat=featureCanvas(iconCropFromTemplate(im));templates.push({...m,feat,img:im});let div=document.createElement('div');div.className='templateItem';div.innerHTML=`<img src="${m.file}"/><b>${m.code}</b><br/>${m.name.replaceAll('_',' ')}`;tv.appendChild(div);let opt=document.createElement('option');opt.value=m.id;opt.textContent=`${m.code} ${m.name}`;sel.appendChild(opt)}$('result').textContent='โหลด Template ครบ 13 ประเภทแล้ว'}
$('upload').onchange=e=>{let f=e.target.files[0];if(f)setImageBlob(f)};$('btnPaste').onclick=paste;$('btnAnalyze').onclick=analyze;$('btnApply').onclick=apply;$('btnUndo').onclick=undo;$('btnSuggest').onclick=suggest;$('btnReset').onclick=()=>{reset();$('result').textContent='ล้างข้อมูลแล้ว'};$('btnClearTray').onclick=()=>{traySlots=[];syncTray();renderTray();$('result').textContent='ล้างถาดแล้ว'};$('btnEdit').onclick=()=>{editMode=!editMode;$('editPanel').classList.toggle('hidden',!editMode);$('btnEdit').textContent=editMode?'✅ ปิดแก้ไข':'✏️ แก้ไข';tiles.forEach(t=>t.selected=false);draw()};$('btnRedetect').onclick=()=>{let n=detectIcons();$('result').textContent=`Detect icon ใหม่ ${n} จุด`};$('btnActivateSelected').onclick=toggleSel;$('btnDelete').onclick=delSel;$('btnSetType').onclick=setType;$('iconSize').oninput=e=>$('iconSizeLabel').textContent=e.target.value;$('confThreshold').oninput=e=>$('confLabel').textContent=e.target.value;
canvas.addEventListener('pointerdown',e=>{let p=clientToImage(e.clientX,e.clientY);pointerDownInfo={x:e.clientX,y:e.clientY,time:Date.now()}});canvas.addEventListener('pointerup',e=>{if(!pointerDownInfo)return;let moved=Math.hypot(e.clientX-pointerDownInfo.x,e.clientY-pointerDownInfo.y);if(moved<8)tap(e.clientX,e.clientY);pointerDownInfo=null});
pasteCatcher.addEventListener('paste',async e=>{let cd=e.clipboardData;if(!cd)return;if(cd.items){for(let it of cd.items){if(it.type&&it.type.startsWith('image/')){let b=it.getAsFile();if(b){e.preventDefault();await setImageBlob(b);return}}}}});window.addEventListener('resize',()=>{if(img)resize()});renderTray();resize();loadTemplates();