const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),pasteCatcher=$('pasteCatcher');
const TEMPLATE_META=[
 {id:1,code:'T01',name:'blue_microphones',file:'templates/T01_blue_microphones.jpeg'},
 {id:2,code:'T02',name:'purple_guitar',file:'templates/T02_purple_guitar.jpeg'},
 {id:3,code:'T03',name:'pink_drum',file:'templates/T03_pink_drum.jpeg'},
 {id:4,code:'T04',name:'blue_music_note',file:'templates/T04_blue_music_note.jpeg'},
 {id:5,code:'T05',name:'green_music_notes',file:'templates/T05_green_music_notes.jpeg'},
 {id:6,code:'T06',name:'blue_drum_set',file:'templates/T06_blue_drum_set.jpeg'},
 {id:7,code:'T07',name:'blue_turntable',file:'templates/T07_blue_turntable.jpeg'},
 {id:8,code:'T08',name:'pink_record_disc',file:'templates/T08_pink_record_disc.jpeg'},
 {id:9,code:'T09',name:'pink_headphones',file:'templates/T09_pink_headphones.jpeg'},
 {id:10,code:'T10',name:'black_piano',file:'templates/T10_black_piano.jpeg'},
 {id:11,code:'T11',name:'red_keyboard',file:'templates/T11_red_keyboard.jpeg'},
 {id:12,code:'T12',name:'yellow_tambourine',file:'templates/T12_yellow_tambourine.jpeg'},
 {id:13,code:'T13',name:'orange_accordion',file:'templates/T13_orange_accordion.jpeg'}
];
const colors=['#00C853','#2962FF','#AA00FF','#FF6D00','#00B8D4','#D50000','#C51162','#64DD17','#6200EA','#0091EA','#795548','#607D8B','#F50057'];
let templates=[],img=null,imgW=0,imgH=0,view={scale:1,offsetX:0,offsetY:0},dpr=devicePixelRatio||1,pointers=new Map(),lastPinchDist=null,pointerDownInfo=null,suppressNextTap=false;
let tiles=[],nextId=1,traySlots=[],trayCounts=new Map(),suggestionId=null,history=[],editMode=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function colorForType(i){return colors[((i||1)-1)%colors.length]}
function rect(){return canvas.getBoundingClientRect()}function disp(){let r=rect(),w=Math.max(320,r.width||canvas.parentElement.clientWidth||360);return{width:w,height:img?w*imgH/imgW:w*1.6}}function baseScale(){return img?disp().width/imgW:1}
function cssToImage(x,y){let s=baseScale()*view.scale;return{ix:(x-view.offsetX)/s,iy:(y-view.offsetY)/s}}function clientToImage(x,y){let r=rect();return cssToImage(x-r.left,y-r.top)}
function resizeCanvas(){dpr=devicePixelRatio||1;let d=disp();canvas.style.height=d.height+'px';canvas.width=Math.round(d.width*dpr);canvas.height=Math.round(d.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function draw(){let d=disp();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,d.width,d.height);if(!img){ctx.fillStyle='#f2f2f2';ctx.fillRect(0,0,d.width,d.height);ctx.fillStyle='#777';ctx.font='14px system-ui';ctx.fillText('Paste หรือ Upload รูปก่อน',16,28);return}ctx.save();let s=baseScale()*view.scale;ctx.translate(view.offsetX,view.offsetY);ctx.scale(s,s);ctx.drawImage(img,0,0,imgW,imgH);for(let t of tiles){let x=t.cx-t.w/2,y=t.cy-t.h/2;ctx.globalAlpha=t.active?1:.32;ctx.setLineDash(t.active?[]:[8/s,5/s]);ctx.lineWidth=(t.selected?5:3)/s;ctx.strokeStyle=t.selected?'#FFD600':t.color;ctx.strokeRect(x,y,t.w,t.h);ctx.fillStyle='rgba(0,0,0,.74)';ctx.font=`${14/s}px system-ui`;ctx.fillText(`T${String(t.typeId).padStart(2,'0')} ${Math.round(t.confidence*100)}%`,x+4/s,y+16/s);ctx.globalAlpha=1;ctx.setLineDash([]);if(t.id===suggestionId){ctx.lineWidth=7/s;ctx.strokeStyle='#ff1744';ctx.strokeRect(x-4/s,y-4/s,t.w+8/s,t.h+8/s)}}ctx.restore()}
function renderTray(){let v=$('trayView');v.innerHTML='';for(let i=0;i<7;i++){let s=document.createElement('div');s.className='slot';if(i<traySlots.length){let t=traySlots[i];s.textContent='T'+String(t).padStart(2,'0');s.style.color=colorForType(t);s.style.borderColor=colorForType(t)}v.appendChild(s)}$('trayMeta').textContent=`ขนาดถาด: ${traySlots.length}/7 • นับ: ${[...trayCounts.entries()].map(([k,v])=>`T${String(k).padStart(2,'0')}:${v}`).join(' ')||'-'}`}
function syncTray(){trayCounts=new Map();for(let t of traySlots)trayCounts.set(t,(trayCounts.get(t)||0)+1)}
function reset(){tiles=[];nextId=1;traySlots=[];trayCounts=new Map();suggestionId=null;history=[];renderTray();draw()}
async function setImageBlob(blob){let url=URL.createObjectURL(blob),im=new Image();im.onload=()=>{img=im;imgW=im.naturalWidth;imgH=im.naturalHeight;view={scale:1,offsetX:0,offsetY:0};reset();let sz=Math.round(clamp(imgW/9,60,115));$('tileSize').value=sz;$('tileSizeLabel').textContent=sz;resizeCanvas();$('result').textContent='โหลดรูปแล้ว กด “วิเคราะห์ด้วย Template”'};im.onerror=()=>$('result').textContent='อ่านรูปไม่สำเร็จ';im.src=url}
async function paste(){try{if(navigator.clipboard&&navigator.clipboard.read){let items=await navigator.clipboard.read();for(let it of items){let type=it.types.find(t=>t.startsWith('image/'));if(type){await setImageBlob(await it.getType(type));return}}}}catch(e){}$('result').textContent='ถ้า iOS ไม่อนุญาตอ่าน clipboard ให้แตะค้างแล้วเลือก Paste';pasteCatcher.focus()}
function featureFromCanvas(c){let g=c.getContext('2d'),data=g.getImageData(0,0,64,64).data;let gray=[],hist=new Array(36).fill(0),edge=[0,0,0,0,0,0,0,0];for(let i=0;i<data.length;i+=4){let r=data[i],gg=data[i+1],b=data[i+2],br=r*.299+gg*.587+b*.114;gray.push(br);hist[Math.min(11,Math.floor(r/22))]++;hist[12+Math.min(11,Math.floor(gg/22))]++;hist[24+Math.min(11,Math.floor(b/22))]++}for(let y=1;y<63;y+=2){for(let x=1;x<63;x+=2){let gx=gray[y*64+x+1]-gray[y*64+x-1],gy=gray[(y+1)*64+x]-gray[(y-1)*64+x],mag=Math.sqrt(gx*gx+gy*gy);let ang=Math.atan2(gy,gx)+Math.PI,bin=Math.min(7,Math.floor(ang/(Math.PI*2)*8));edge[bin]+=mag}}let bits=new Uint8Array(64),k=0;for(let y=0;y<8;y++)for(let x=0;x<8;x++){let sum=0;for(let yy=0;yy<8;yy++)for(let xx=0;xx<8;xx++)sum+=gray[(y*8+yy)*64+(x*8+xx)];bits[k++]=sum/64>128?1:0}let norm=Math.sqrt(hist.reduce((a,b)=>a+b*b,0))||1;hist=hist.map(v=>v/norm);let enorm=Math.sqrt(edge.reduce((a,b)=>a+b*b,0))||1;edge=edge.map(v=>v/enorm);return{bits,hist,edge}}
function centerCropFromImage(image){let c=document.createElement('canvas');c.width=64;c.height=64;let g=c.getContext('2d'),w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;let sx=w*.24,sy=h*.22,sw=w*.52,sh=h*.58;g.drawImage(image,sx,sy,sw,sh,0,0,64,64);return c}
function centerCropTile(ix,iy,size){let c=document.createElement('canvas');c.width=64;c.height=64;let g=c.getContext('2d');let sx=ix-size*.25,sy=iy-size*.28,sw=size*.50,sh=size*.56;sx=clamp(sx,0,imgW-sw);sy=clamp(sy,0,imgH-sh);g.drawImage(img,sx,sy,sw,sh,0,0,64,64);return c}
function featureTile(ix,iy,size){return featureFromCanvas(centerCropTile(ix,iy,size))}
function distance(a,b){let h=0;for(let i=0;i<a.bits.length;i++)if(a.bits[i]!==b.bits[i])h++;let dot=0;for(let i=0;i<a.hist.length;i++)dot+=a.hist[i]*b.hist[i];let edot=0;for(let i=0;i<a.edge.length;i++)edot+=a.edge[i]*b.edge[i];return h/64*.48+(1-dot)*.34+(1-edot)*.18}
function classify(feat){let best=null,second=null;for(let tm of templates){let d=distance(feat,tm.feat);if(!best||d<best.d){second=best;best={template:tm,d}}else if(!second||d<second.d){second={template:tm,d}}}let margin=second?Math.max(0,second.d-best.d):0;let conf=clamp(1-(best.d/0.55)+margin*.35,0,1);return{typeId:best.template.id,confidence:conf,dist:best.d,name:best.template.name}}
function addTile(ix,iy,active=true){let size=parseInt($('tileSize').value,10);if(ix<0||iy<0||ix>imgW||iy>imgH)return null;let feat=featureTile(ix,iy,size),cls=classify(feat),thr=parseInt($('confThreshold').value,10)/100;let t={id:nextId++,cx:ix,cy:iy,w:size,h:size,feat,typeId:cls.typeId,confidence:cls.confidence,color:colorForType(cls.typeId),active:active&&cls.confidence>=thr,selected:false};tiles.push(t);draw();return t}
function reclassifyAll(){let thr=parseInt($('confThreshold').value,10)/100;for(let t of tiles){let cls=classify(t.feat);t.typeId=cls.typeId;t.confidence=cls.confidence;t.color=colorForType(t.typeId);if(t.confidence<thr)t.active=false}draw()}
function hit(ix,iy){for(let i=tiles.length-1;i>=0;i--){let t=tiles[i];if(ix>=t.cx-t.w/2&&ix<=t.cx+t.w/2&&iy>=t.cy-t.h/2&&iy<=t.cy+t.h/2)return t}return null}
function iou(a,b){let ax0=a.cx-a.w/2,ay0=a.cy-a.h/2,ax1=a.cx+a.w/2,ay1=a.cy+a.h/2,bx0=b.cx-b.w/2,by0=b.cy-b.h/2,bx1=b.cx+b.w/2,by1=b.cy+b.h/2,ix=Math.max(0,Math.min(ax1,bx1)-Math.max(ax0,bx0)),iy=Math.max(0,Math.min(ay1,by1)-Math.max(ay0,by0)),inter=ix*iy,u=a.w*a.h+b.w*b.h-inter;return u?inter/u:0}
function stats(data,x0,y0,w,h,stride){let W=data.width,A=data.data,n=0,sum=0,sum2=0,edge=0;x0=clamp(Math.floor(x0),0,W-1);y0=clamp(Math.floor(y0),0,data.height-1);let x1=clamp(Math.floor(x0+w),0,W-1),y1=clamp(Math.floor(y0+h),0,data.height-1);for(let y=y0;y<y1;y+=stride)for(let x=x0;x<x1;x+=stride){let p=(y*W+x)*4,br=(A[p]+A[p+1]+A[p+2])/3;sum+=br;sum2+=br*br;n++;if(x+stride<x1&&y+stride<y1){let p2=(y*W+x+stride)*4,p3=((y+stride)*W+x)*4,br2=(A[p2]+A[p2+1]+A[p2+2])/3,br3=(A[p3]+A[p3+1]+A[p3+2])/3;edge+=Math.abs(br-br2)+Math.abs(br-br3)}}let mean=sum/Math.max(1,n),variance=sum2/Math.max(1,n)-mean*mean;return{mean,variance,edge:edge/Math.max(1,n)}}
function detectTiles(autoActive=true){if(!img){$('result').textContent='โหลดรูปก่อน';return 0}tiles=[];nextId=1;suggestionId=null;let size=parseInt($('tileSize').value,10),sens=parseInt($('sens').value,10),scale=Math.min(1,900/imgW),pc=document.createElement('canvas');pc.width=Math.round(imgW*scale);pc.height=Math.round(imgH*scale);let p=pc.getContext('2d');p.drawImage(img,0,0,pc.width,pc.height);let data=p.getImageData(0,0,pc.width,pc.height),ss=size*scale,step=Math.max(10,Math.round(ss/3.25)),cand=[];for(let y=ss/2;y<pc.height-ss/2;y+=step)for(let x=ss/2;x<pc.width-ss/2;x+=step){let st=stats(data,x-ss/2,y-ss/2,ss,ss,Math.max(2,Math.round(ss/18))),inner=stats(data,x-ss*.25,y-ss*.28,ss*.5,ss*.56,Math.max(2,Math.round(ss/20)));let score=(st.mean-95)*1.05+Math.sqrt(Math.max(0,inner.variance))*2.05+st.edge*.52;if(st.mean>92&&inner.variance>135&&score>128-sens)cand.push({cx:x/scale,cy:y/scale,w:size,h:size,score})}cand.sort((a,b)=>b.score-a.score);let sel=[];for(let c of cand){if(sel.length>=72)break;if(sel.every(o=>iou(c,o)<.25))sel.push(c)}for(let c of sel)addTile(c.cx,c.cy,autoActive);draw();return tiles.length}
function analyze(){let n=detectTiles(true);if(!n){$('result').textContent='ตรวจไม่พบไพ่ ลองเพิ่มความไวหรือแตะเพิ่มเองในโหมดแก้ไข';return}let uncertain=tiles.filter(t=>!t.active).length;suggest();$('result').innerHTML+=`<br><span class="small">ตรวจพบ ${n} กรอบ • confidence ต่ำ/ปิดใช้งาน ${uncertain} กรอบ • ใช้ Template 13 ประเภท</span>`}
function suggest(){let pool=tiles.filter(t=>t.active);if(!pool.length){suggestionId=null;draw();$('result').textContent='ยังไม่มีไพ่ที่ Active/confidence ผ่านขั้นต่ำ';return false}let cnt=new Map();for(let t of pool)cnt.set(t.typeId,(cnt.get(t.typeId)||0)+1);let trayTypes=new Set(traySlots),best=null;for(let t of pool){let inTray=trayCounts.get(t.typeId)||0,score=0,reason=[];if(inTray===2){score+=1000;reason.push('ปิดครบ 3')}else if(inTray===1){score+=220;reason.push('ทำเป็นคู่')}if((cnt.get(t.typeId)||0)>=2){score+=75;reason.push('มีชนิดเดียวกันหลายใบ')}if(traySlots.length>=5&&!trayTypes.has(t.typeId)){score-=180;reason.push('ถาดใกล้เต็ม')}if(trayTypes.has(t.typeId))score+=45;score+=t.confidence*20;score+=(1000-t.id)*1e-6;if(!best||score>best.score)best={tile:t,score,reason}}suggestionId=best.tile.id;draw();$('result').innerHTML=`แนะนำให้กด <b>T${String(best.tile.typeId).padStart(2,'0')}</b> (กรอบแดง) • ${best.reason.join(' • ')||'คะแนนดีที่สุด'} • confidence ${Math.round(best.tile.confidence*100)}%`;return true}
function addTray(type){if(traySlots.length>=7)return{ok:false};traySlots.push(type);syncTray();let cleared=false;if(trayCounts.get(type)===3){let r=0;traySlots=traySlots.filter(t=>(t===type&&r++<3)?false:true);syncTray();cleared=true}renderTray();return{ok:true,cleared}}
function apply(){if(!suggestionId&&!suggest())return;let idx=tiles.findIndex(t=>t.id===suggestionId);if(idx<0)return;history.push({tiles:tiles.map(t=>({...t,feat:{bits:new Uint8Array(t.feat.bits),hist:[...t.feat.hist],edge:[...t.feat.edge]}})),tray:[...traySlots],nextId,suggestionId});let t=tiles[idx],r=addTray(t.typeId);tiles.splice(idx,1);suggestionId=null;draw();$('result').textContent=`บันทึกว่าได้กด T${String(t.typeId).padStart(2,'0')} แล้ว${r.cleared?' • ครบ 3 ลบแล้ว':''}`;setTimeout(suggest,50)}
function undo(){let h=history.pop();if(!h){$('result').textContent='ไม่มีประวัติ Undo';return}tiles=h.tiles.map(t=>({...t,feat:{bits:new Uint8Array(t.feat.bits),hist:[...t.feat.hist],edge:[...t.feat.edge]}}));traySlots=[...h.tray];syncTray();nextId=h.nextId;suggestionId=h.suggestionId;renderTray();draw();$('result').textContent='Undo แล้ว'}
function selected(){return tiles.filter(t=>t.selected)}function deleteSelected(){let before=tiles.length;tiles=tiles.filter(t=>!t.selected);suggestionId=null;draw();$('result').textContent=`ลบ ${before-tiles.length} ใบแล้ว`}function toggleSelectedActive(){let s=selected();if(!s.length){$('result').textContent='เลือกใบก่อน';return}for(let t of s){t.active=!t.active;t.selected=false}draw();$('result').textContent='เปิด/ปิดใบที่เลือกแล้ว'}function setSelectedType(){let s=selected(),type=parseInt($('typeSelect').value,10);if(!s.length){$('result').textContent='เลือกใบก่อนตั้ง Type';return}for(let t of s){t.typeId=type;t.color=colorForType(type);t.confidence=1;t.active=true;t.selected=false}draw();$('result').textContent=`ตั้ง Type เป็น T${String(type).padStart(2,'0')} แล้ว`}
function tap(x,y){if(!img)return;let p=clientToImage(x,y),t=hit(p.ix,p.iy);if(t){if(editMode){t.selected=!t.selected}else{t.active=!t.active}suggestionId=null;draw();return}if(editMode){let nt=addTile(p.ix,p.iy,true);if(nt){nt.selected=true;draw();$('result').textContent='เพิ่มไพ่เองและ match template แล้ว'}}}
async function loadTemplates(){let view=$('templateView'),select=$('typeSelect');for(let meta of TEMPLATE_META){let im=new Image();im.src=meta.file;await new Promise((res,rej)=>{im.onload=res;im.onerror=rej});let feat=featureFromCanvas(centerCropFromImage(im));templates.push({...meta,img:im,feat});let item=document.createElement('div');item.className='templateItem';item.innerHTML=`<img src="${meta.file}"/><b>${meta.code}</b><br/>${meta.name.replaceAll('_',' ')}`;view.appendChild(item);let opt=document.createElement('option');opt.value=meta.id;opt.textContent=`${meta.code} ${meta.name}`;select.appendChild(opt)}$('result').textContent=`โหลด Template Library ครบ ${templates.length}/13 แล้ว`}
$('upload').onchange=e=>{let f=e.target.files[0];if(f)setImageBlob(f)};$('btnPaste').onclick=paste;$('btnAnalyze').onclick=analyze;$('btnApply').onclick=apply;$('btnUndo').onclick=undo;$('btnSuggest').onclick=suggest;$('btnReset').onclick=()=>{reset();$('result').textContent='ล้างข้อมูลแล้ว'};$('btnClearTray').onclick=()=>{traySlots=[];syncTray();renderTray();$('result').textContent='ล้างถาดแล้ว'};$('btnEdit').onclick=()=>{editMode=!editMode;$('editPanel').classList.toggle('hidden',!editMode);$('btnEdit').textContent=editMode?'✅ ปิดแก้ไข':'✏️ แก้ไข';for(let t of tiles)t.selected=false;draw()};$('btnRedetect').onclick=()=>{let n=detectTiles(false);$('result').textContent=`Detect ใหม่ ${n} กรอบ (ส่วนใหญ่ยังไม่ active ถ้า confidence ต่ำ)`};$('btnReclassify').onclick=()=>{reclassifyAll();$('result').textContent='Match Template ใหม่แล้ว'};$('btnActivateSelected').onclick=toggleSelectedActive;$('btnDelete').onclick=deleteSelected;$('btnSetType').onclick=setSelectedType;$('tileSize').oninput=e=>$('tileSizeLabel').textContent=e.target.value;$('sens').oninput=e=>$('sensLabel').textContent=e.target.value;$('confThreshold').oninput=e=>$('confLabel').textContent=e.target.value;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)pointerDownInfo={x:e.clientX,y:e.clientY,time:Date.now()};if(pointers.size===2){let a=[...pointers.values()];lastPinchDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);suppressNextTap=true}});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;let prev=pointers.get(e.pointerId),cur={x:e.clientX,y:e.clientY};pointers.set(e.pointerId,cur);if(pointers.size===1){let dx=cur.x-prev.x,dy=cur.y-prev.y;if(Math.abs(dx)+Math.abs(dy)>1){view.offsetX+=dx;view.offsetY+=dy;draw()}}else if(pointers.size===2){let a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(lastPinchDist){let factor=dist/lastPinchDist,newScale=clamp(view.scale*factor,.5,5),r=rect(),mx=(a[0].x+a[1].x)/2-r.left,my=(a[0].y+a[1].y)/2-r.top,before=cssToImage(mx,my);view.scale=newScale;let s=baseScale()*view.scale;view.offsetX=mx-before.ix*s;view.offsetY=my-before.iy*s;draw()}lastPinchDist=dist}});function end(e){let single=pointers.size===1&&pointers.has(e.pointerId);pointers.delete(e.pointerId);if(pointers.size<2)lastPinchDist=null;if(single&&pointerDownInfo&&!suppressNextTap){let moved=Math.hypot(e.clientX-pointerDownInfo.x,e.clientY-pointerDownInfo.y),elapsed=Date.now()-pointerDownInfo.time;if(moved<8&&elapsed<700)tap(e.clientX,e.clientY)}if(pointers.size===0){pointerDownInfo=null;setTimeout(()=>suppressNextTap=false,50)}}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);pointerDownInfo=null;suppressNextTap=false});pasteCatcher.addEventListener('paste',async e=>{let cd=e.clipboardData;if(!cd)return;if(cd.items){for(let it of cd.items){if(it.type&&it.type.startsWith('image/')){let b=it.getAsFile();if(b){e.preventDefault();await setImageBlob(b);return}}}}$('result').textContent='Paste ไม่พบรูป'});window.addEventListener('resize',()=>{if(img)resizeCanvas()});renderTray();resizeCanvas();loadTemplates().catch(e=>{$('result').textContent='โหลด Template ไม่สำเร็จ: '+e.message});